/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/el9rHvEANUz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function Contact() {
  return (
    <div className="w-full">
      <div className="container prose text-center mx-auto">
        <h2 className="text-3xl font-bold">Contact us</h2>
        <p className="max-w-[600px] text-gray-500 md:mx-auto dark:text-gray-400">
          Have a question or need assistance? Send us a message and we&apos;ll
          get back to you as soon as possible.
        </p>
      </div>
      <div className="container max-w-sm py-12 mx-auto">
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea
              className="min-h-[100px]"
              id="message"
              placeholder="Enter your message"
            />
          </div>
          <Button>Send message</Button>
          {/* TODO: Make the form work */}
        </div>
      </div>
    </div>
  );
}
