/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xyfxfMNDIat
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { JSX, SVGProps } from "react";

export function Pricing() {
  return (
    <section className="w-full pb-8">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
              The Perfect Plan
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              Your source for scholarly satire
            </h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Choose the plan that fits your needs. Whether you&apos;re writing
              a tongue-in-cheek article or a full-blown academic parody,
              we&apos;ve got you covered with our easy-to-use platform and
              hilarious templates.
            </p>
            <br />
          </div>
        </div>
        <div className="grid max-w-sm gap-6 mx-auto items-start sm:max-w-3xl sm:grid-cols-2 lg:max-w-5xl lg:grid-cols-3 lg:gap-8">
          <div className="flex flex-col rounded-lg border border-gray-200 border-gray-200 bg-white shadow-sm overflow-hidden dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
            <div className="bg-gray-50 p-6 dark:bg-gray-800">
              <h3 className="text-xl font-bold tracking-tight">
                The Undergrad Special
              </h3>
              <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                Perfect for pranks and memes
              </p>
            </div>
            <div className="grid gap-4 p-6 items-start">
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Authentic-looking research papers
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Hilarious and realistic citations
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Easy-to-use platform
              </div>
            </div>
            <div className="p-6 border-t border-gray-200 dark:border-gray-800">
              <div className="font-bold text-xl">$0/month</div>
              <div className="text-sm text-gray-500">Billed never</div>
            </div>
            <Link href="/signin" className="w-full">
              {/* TODO: update to premium signup / buy link */}
              <Button
                size="sm"
                variant="outline"
                className="w-full justify-center"
              >
                Choose Plan
              </Button>
            </Link>
          </div>
          <div className="flex flex-col rounded-lg border-2 border-indigo-600 bg-white shadow-lg overflow-hidden dark:border-gray-950 dark:bg-gray-950">
            <div className="bg-indigo-600 p-6">
              <h3 className="text-xl font-bold tracking-tight text-gray-50">
                The Phony Ph.D.
              </h3>
              <p className="mt-1 text-sm text-gray-50/70 dark:text-gray-50/70">
                Serious satire for the scholarly
              </p>
            </div>
            <div className="grid gap-4 p-6 items-start">
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Authentic-looking research papers
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Hilarious and realistic citations
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Easy-to-use platform
              </div>
              <div className="flex items-center gap-2 font-bold">
                <CheckIcon className="h-4 w-4" />
                Premium quality generation
              </div>
            </div>
            <div className="p-6 border-t border-gray-200 dark:border-gray-800">
              <div className="font-bold text-xl">$9/month</div>
              <div className="text-sm text-gray-500">Billed annually</div>
            </div>
            <Link href="/signin" className="w-full">
              {/* TODO: update to premium signup / buy link */}
              <Button
                size="sm"
                variant="outline"
                className="w-full justify-center"
              >
                Choose Plan
              </Button>
            </Link>
          </div>
          <div className="flex flex-col rounded-lg border border-gray-200 border-gray-200 bg-white shadow-sm overflow-hidden dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950">
            <div className="bg-gray-50 p-6 dark:bg-gray-800">
              <h3 className="text-xl font-bold tracking-tight">
                The Academic Absurdity
              </h3>
              <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                Peer-reviewed parody for professionals
              </p>
            </div>
            <div className="grid gap-4 p-6 items-start">
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Authentic-looking research papers
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Hilarious and realistic citations
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Easy-to-use platform
              </div>
              <div className="flex items-center gap-2">
                <CheckIcon className="h-4 w-4" />
                Premium quality generation
              </div>
              <div className="flex items-center gap-2 font-bold">
                <CheckIcon className="h-4 w-4" />
                Customize features
              </div>
              <div className="flex items-center gap-2 font-bold">
                <CheckIcon className="h-4 w-4" />
                SSO and SOC 2 Compliance
              </div>
            </div>
            <div className="p-6 border-t border-gray-200 dark:border-gray-800">
              <div className="font-bold text-xl">Contact Us</div>
              <div className="text-sm text-gray-500">Flexible billing</div>
            </div>
            <Link href="/contact" className="w-full">
              <Button
                size="sm"
                variant="outline"
                className="w-full justify-center"
              >
                Contact Us
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
