/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/m7fB3tnyJMK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function SearchInput() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <CardTitle className="text-lg">Submit Paper Topic</CardTitle>
        <CardDescription>
          Submit your paper&apos;s topic and let input and contribute to the
          conversation.
        </CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="space-y-1">
          <Label htmlFor="llm-input">Topic Input</Label>
          <Textarea id="llm-input" placeholder="Enter your paper's topic." />
        </div>
      </CardContent>
      <CardFooter>
        <Button size="sm">Submit</Button>
      </CardFooter>
    </Card>
  );
}
