/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7Z1ov4m18mi
 */
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

export function SplashPage() {
  return (
    <main className="flex-1">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-40">
        <div className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6">
          <div className="text-center space-y-2">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
              Generate Fake Papers
            </h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Create realistic-looking joke research papers with our
              customizable templates and realistic citations.
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            <form className="flex space-x-2">
              <Input
                className="max-w-lg flex-1"
                placeholder="Enter your email"
                type="email"
              />
              <Button type="submit">Get Started</Button>
            </form>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Enter your email to get notified when we launch.
              <Link className="underline underline-offset-2" href="#">
                Terms & Conditions
              </Link>
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Features
            </h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Learn more about our features that make our fake papers look real.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 sm:gap-10 lg:grid-cols-3 lg:gap-12">
            <div className="space-y-4">
              <h3 className="text-2xl font-bold">Customizable Templates</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Choose from a variety of academic disciplines and customize the
                look of your paper.
              </p>
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-bold">Realistic Citations</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Our AI-generated citations look just like the real thing.
              </p>
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-bold">Academic Disciplines</h3>
              <p className="text-gray-500 dark:text-gray-400">
                We cover everything from Astrophysics to Zoology.
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}

function FileTextIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
      <line x1="16" x2="8" y1="13" y2="13" />
      <line x1="16" x2="8" y1="17" y2="17" />
      <line x1="10" x2="8" y1="9" y2="9" />
    </svg>
  );
}
